### ISSUE TITLE
超级医生无法使用

### ISSUE THREAD

**Issue by XjDGitHub** [zhousg/patient-h5-note#1]
![image](https://github.com/zhousg/patient-h5-note/assets/90093451/d4587ec6-e29b-4c5c-ac0a-b25d0cfec631)

**Comment by zhousg** [comment]
<img width="399" alt="image" src="https://github.com/zhousg/patient-h5-note/assets/15833290/2717e610-02fa-49e9-b74f-0fe18d41a2ac">
没问题哈
